version: 2
sources:
  - name: staging
    database: kestra-sandbox-449808
    schema: ny_taxi_all_trips
    tables:
      - name: green_trips
      - name: yellow_trips
      - name: fhv_trips
  - name: stg_staging__green_trips  # Old name
    description: "Green taxi trips staging table"

  - name: stg_green_trips  # New name
    description: "Renamed table"
      